# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project: weep
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/netflix/weep/version.Version={{.Version}} -X github.com/netflix/weep/version.Commit={{.CommitDate}} -X github.com/netflix/weep/version.Date={{.Date}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      post:
        - upx "{{ .Path }}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: true
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - weep
    image_templates:
      - "netflix/{{.ProjectName}}:latest"
      - "netflix/{{.ProjectName}}:{{ .Tag }}"
      - "netflix/{{.ProjectName}}:v{{ .Major }}"
      - "netflix/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:latest"
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:{{ .Tag }}"
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:v{{ .Major }}"
      - "docker.pkg.github.com/netflix/{{.ProjectName}}/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
