name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - uses: pre-commit/action@v2.0.0
